# Generated by Django 2.2 on 2019-05-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190514_1120'),
    ]

    operations = [
    ]
